### ISSUE TITLE
Release? 

### ISSUE THREAD

**Issue by jrbourbeau** [coiled/dask-bigquery#18]
There are some groups who would like to give `dask-bigquery` a try and provide some initial feedback (cc @quasiben). While there is still some ongoing work related to credentials over in https://github.com/coiled/dask-bigquery/pull/11, I think `dask-bigquery` will work as is when both the client + workers have default credentials configured (xref https://github.com/coiled/dask-bigquery/pull/11#issuecomment-943704500). Given this, there's probably value in pushing out a `dask-bigquery` release now and then continuing with https://github.com/coiled/dask-bigquery/pull/11 as a follow-up enchancement. 

@ncclementi @bnaul thoughts?

**Comment by ncclementi** [comment]
I've just opened a PR https://github.com/coiled/dask-bigquery/pull/19 to set some things straight regarding requirements, I have some doubts with certain imports, whether we should include them or not. Once that is cleared and merged I think we can go ahead and release.
