### ISSUE TITLE
How do we create tests for this package?

### ISSUE THREAD

**Issue by ncclementi** [coiled/dask-bigquery#2]
We need to add tests but I'm wondering how do we go about this, some questions that come to mind that I don't have answers are: 
- How do we create the clients only for the purpose of CI testing?
- How do we manage credentials/authentication in this case

I was looking at `pandas-gbq`, and it seems the way to go might be using mock tests like what is used [here](https://github.com/googleapis/python-bigquery-pandas/blob/41d290d17616149a6db86702bad0faa90c61a2fd/tests/unit/test_context.py). Is that the only option or I am missing something.

cc: @jrbourbeau @bnaul

**Comment by bnaul** [comment]
It looks like for `dask-snowflake` they're just doing real queries with some private credentials https://github.com/coiled/dask-snowflake/blob/main/dask_snowflake/tests/test_core.py

Seems like a reasonable approach to take here as well, especially because there's lot of public BigQuery datasets already that could be used for testing and folks could still run locally provided they have their own GCP account (ideally they would run even on the free tier)

**Comment by bnaul** [comment]
Here's a simple test that we use
```
import pytest

from util.bigquery import gbq_as_dask_df

TEST_QUERY = "SELECT state, state_name FROM `model-159019.sample_data.states` ORDER BY state"


def test_gbq_to_dask():
    ddf = gbq_as_dask_df("model-159019", "sample_data", "states", fields=["state", "state_name"])
    assert ddf.columns.tolist() == ["state", "state_name"]
    assert len(ddf) >= 50
    # Test across processes/pickling
    ddf.compute(scheduler="processes")


@pytest.mark.parametrize(
    "fields",
    ([], ["state_name"], ["state", "state_name"]),
    ids=["no_fields", "missing_partition_field", "fields"],
)
def test_gbq_to_dask_partitioning(fields):
    partitions = ["DE", "RI"]
    ddf = gbq_as_dask_df(
        "model-159019",
        "sample_data",
        "states",
        partition_field="state",
        partitions=partitions,
        fields=fields,
    )
    loaded = set(ddf.columns) | {ddf.index.name}
    if fields:
        assert loaded == set(fields) | {"state"}
    else:  # all columns loaded
        assert loaded >= set(["state", "state_name"])
    assert ddf.npartitions == len(partitions)
    assert list(ddf.divisions) == sorted(ddf.divisions)
    assert len(ddf) == len(partitions)
    # Test across processes/pickling
    ddf.compute(scheduler="processes")


# write test, skip for now
# from util.bigquery dask_df_to_gbq
# _TEMP_BQ_DATASET = "tmp"
# @pytest.mark.timeout(240)
# def test_dask_df_to_gbq():
#     df = pd._testing.makeDataFrame().rename_axis("uid").sort_index().reset_index()
#     df["timestamp"] = pd.date_range("now", periods=len(df), freq="1d").tz_localize("UTC")
#     bq_schema = [
#         bigquery.SchemaField(col, bigquery._pandas_helperes._PANDAS_DTYPE_TO_BQ.get(dtype))
#         for col, dtype in df.dtypes.astype(str).items()
#     ]
#     pa_schema = dict()
#     for col, np_dtype in df.dtypes.items():
#         if col == "timestamp":
#             pa_schema[col] = pyarrow.timestamp("ns", tz="UTC")
#         elif np_dtype == np.dtype("O"):
#             pa_schema[col] = pyarrow.string()
#         else:
#             pa_schema[col] = pyarrow.from_numpy_dtype(np_dtype)
#     pa_schema = pyarrow.schema(pa_schema)
#
#     ddf = dd.from_pandas(df, npartitions=2)
#     tmp_table = f"temp_{uuid4().hex}"
#     dask_df_to_gbq(
#         ddf,
#         None,
#         _TEMP_BQ_DATASET,
#         tmp_table,
#         bq_schema=bq_schema,
#         pa_schema=pa_schema,
#         partition_by="timestamp",
#         cluster_by="uid",
#     )
#
#     reloaded = read_gbq(f"SELECT * FROM {_TEMP_BQ_DATASET}.{tmp_table} ORDER BY uid")
#     assert df.equals(reloaded)
```

**Comment by ncclementi** [comment]
> It looks like for `dask-snowflake` they're just doing real queries with some private credentials https://github.com/coiled/dask-snowflake/blob/main/dask_snowflake/tests/test_core.py

> Seems like a reasonable approach to take here as well, especially because there's lot of public BigQuery datasets already that could be used for testing and folks could still run locally provided they have their own GCP account (ideally they would run even on the free tier)

@bnaul That's a good point, I was wondering how would we go about being able to run the tests in CI. It seems this approach is only for running locally. 


> Here's a simple test that we use
> ```
> import pytest
> 
> from util.bigquery import gbq_as_dask_df
> 
> TEST_QUERY = "SELECT state, state_name FROM `model-159019.sample_data.states` ORDER BY state"
> 
> 
> def test_gbq_to_dask():
>     ddf = gbq_as_dask_df("model-159019", "sample_data", "states", fields=["state", "state_name"])
>     assert ddf.columns.tolist() == ["state", "state_name"]
>     assert len(ddf) >= 50
>     # Test across processes/pickling
>     ddf.compute(scheduler="processes")
> 
> 
> @pytest.mark.parametrize(
>     "fields",
>     ([], ["state_name"], ["state", "state_name"]),
>     ids=["no_fields", "missing_partition_field", "fields"],
> )
> def test_gbq_to_dask_partitioning(fields):
>     partitions = ["DE", "RI"]
>     ddf = gbq_as_dask_df(
>         "model-159019",
>         "sample_data",
>         "states",
>         partition_field="state",
>         partitions=partitions,
>         fields=fields,
>     )
>     loaded = set(ddf.columns) | {ddf.index.name}
>     if fields:
>         assert loaded == set(fields) | {"state"}
>     else:  # all columns loaded
>         assert loaded >= set(["state", "state_name"])
>     assert ddf.npartitions == len(partitions)
>     assert list(ddf.divisions) == sorted(ddf.divisions)
>     assert len(ddf) == len(partitions)
>     # Test across processes/pickling
>     ddf.compute(scheduler="processes")
> 

> the `sample_data.states` table is a copy of `bigquery-public-data:geo_us_boundaries.states`, I think we had to make our own copy bc we didn't have BQ Storage API permissions for the public version. This might have been the same thing you ran into @ncclementi with the other public tables that weren't working for you. Maybe the covid stats one that you used instead would work here as well?

Even for the case of the covid data I had to make my own copy because of the same permissions. Which is another extra step required for testing even if it's done locally. It seems the datasets are public but we don't have BQ Storage API permissions and that forces us to make a copy of the data.

**Comment by ncclementi** [comment]
@bnaul it seems local testing it is. After bouncing ideas with @jrbourbeau it seems for now is the way to go. However, 
I'm trying to write the tests and use the data you suggested (a copy of `bigquery-public-data:geo_us_boundaries.states`) but can't seem to find it. Whenever I look for `bigquery-public-data` on the console I only see the covid-19 dataset. Am I missing something? 
![Screen Shot 2021-08-16 at 5 18 13 PM](https://user-images.githubusercontent.com/7526622/129631174-df6e95fd-435b-471b-b752-2f10a3ca312e.png)

**Comment by bnaul** [comment]
Strange...does this link work for you? https://console.cloud.google.com/bigquery?project=bigquery-public-data&p=bigquery-public-data&d=geo_us_boundaries&page=table&t=states&ws=!1m9!1m3!3m2!1sbigquery-public-data!2sgeo_us_boundaries!1m4!4m3!1sbigquery-public-data!2sgeo_us_boundaries!3sstates

**Comment by ncclementi** [comment]
Interesting, the link works but if I try to navigate to it through the console I can't. Well, I'll make a copy and play around with the dataset. Thanks for the link

**Comment by ncclementi** [comment]
@bnaul ups not so fast, it seems I can see it but not access it. I tried to copy it and got 
```
Access Denied: Dataset bigquery-public-data:geo_us_boundaries: Permission bigquery.tables.create denied on dataset bigquery-public-data:geo_us_boundaries (or it may not exist).

```

**Comment by ncclementi** [comment]
@bnaul it seems the data might not exist or that there is some problem with it, because after copying the table I get an empty table and this shows on the console. I think I'll have to rely on the covid data then. 

![Screen Shot 2021-08-16 at 6 15 39 PM](https://user-images.githubusercontent.com/7526622/129636300-3939d385-ba60-4427-bb65-473ac3b47e5b.png)

**Comment by bnaul** [comment]
COVID data seems fine, I promise this data exists though 😅 
```
(.venv) ➜  model git:(master) ✗ bq query --nouse_legacy_sql "SELECT COUNT(*) FROM bigquery-public-data.geo_us_boundaries.states"

+-----+
| f0_ |
+-----+
|  56 |
+-----+
```

**Comment by ncclementi** [comment]
Thanks @bnaul I also noticed while trying to experiment with some data for testing, that if I upload data using `pandas_gbq` and provide the keyword `chunksize=n`  then when reading this data back with dask version of `read_gbq` it read in partitions that each has chunksize rows. Do you know what is the magic happening behind this?

**Comment by ncclementi** [comment]
Closing this since we got CI up and running 🎉
