### ISSUE TITLE
Schedule release

### ISSUE THREAD

**Issue by ncclementi** [coiled/dask-bigquery#35]
Folks, I noticed that we haven't done a release since we merged https://github.com/coiled/dask-bigquery/pull/33 and we probably should. 

I'm happy to take this one on. Let me know if you have any objections or anything else we should include in this release. Should we drop python 3.7 support since dask has dropped it?

cc: @jrbourbeau @bnaul

**Comment by bnaul** [comment]
sgtm on both!

**Comment by ncclementi** [comment]
I was going to make a release, and we were having some linting issues, when trying to fix this issue, I opened a PR, and found that we have failures on windows, but not sure where this is coming from as it is a Seg Fault. 
https://github.com/coiled/dask-bigquery/runs/6099039573?check_suite_focus=true#step:6:92

I feel I have seen something similar over dask, but can't recall what the problem was. @jrbourbeau DO you have any clue where this is coming from?

**Comment by ncclementi** [comment]
So it seems the Windows CI seg fault came from `grpcio=1.45` I pinned it to `1.44` on the `environment.yml` and we have a green CI. However, I wonder if we need to add this as a requirement? not quite sure what's the best way to approach this.

**Comment by ncclementi** [comment]
Close after https://github.com/conda-forge/dask-bigquery-feedstock/pull/1
