### ISSUE TITLE
Adding bigquery push function

### ISSUE THREAD

**Issue by BasileGoussard** [coiled/dask-bigquery#42]
Adding a function like pandas_gbq  to implement a method like 
pandas_gbq.to_gbq(df, table_id, project_id=project_id)

It would help users directly transfer data from coiled cluster to bigquery without the need to transfer the data locally.

**Comment by bnaul** [comment]
There's a discussion already in #3; I agree that this would be very nice, but I think it's a bit tricky to implement (the way that I typically do this is `ddf.to_parquet("gs://some_temp_path/"); bigquery.Client.load_table_from_uri("gs://some_temp_path/")` but I think we were hoping to find a way to avoid using cloud storage.
