### ISSUE TITLE
Support configuring `types_mapper` in `read_gbq`

### ISSUE THREAD

**Issue by bnaul** [coiled/dask-bigquery#45]
https://github.com/googleapis/python-bigquery/pull/1529 and https://github.com/googleapis/python-bigquery/pull/1547 have recently added arguments for overriding the default type conversions performed by `record_batch.to_pandas()`; this allows, for example, loading string data directly into dtype `string[pyarrow]` (which can be quite a bit more [efficient](https://www.coiled.io/blog/pyarrow-strings-in-dask-dataframes)) without doing any expensive conversions after the fact.

I think we could basically just copy the implementation from the above PRs, same kwarg names and everything. Anyone see any potential issues @jrbourbeau @j-bennet @ncclementi?

**Comment by j-bennet** [comment]
@bnaul You can already provide a custom mapper in `read_dbq` as part of `arrow_options`:

https://github.com/coiled/dask-snowflake/blob/42cb99e4e35aeb18f7ede95badba8f20a4113378/dask_snowflake/core.py#L215-L217

**Comment by bnaul** [comment]
Ha well this looks great, but unfortunately that's `dask-snowflake` and this is `dask-bigquery` 😅 but yeah that's basically what I had in mind! Do you think the same `arrow_options` approach makes sense here? As opposed to copying the many many kwargs that they expose in `google.cloud.bigquery.QueryJob.to_dataframe()`.

**Comment by j-bennet** [comment]
:) :) :) scratch that, I'm contributing to `dask-snowflake` and `dask-bigquery` right now, and completely confused which one we're talking about.

Yes, I think `arrow_kwargs` would make sense in `read_dbq`. It would not take much, we would need to pass those kwargs through to the point where we call `to_pandas` on a pyarrow record batch:

https://github.com/coiled/dask-bigquery/blob/876ddb855e8683e10f55280f9de77bc44c487d5a/dask_bigquery/core.py#L45-L48
