### ISSUE TITLE
Give proper attribution to @bnaul

### ISSUE THREAD

**Issue by ncclementi** [coiled/dask-bigquery#5]
This project was based on the contributions made by @bnaul  on this [gist](https://gist.github.com/bnaul/4819f045ccbee160b60a530b6cfc0c98#file-dask_bigquery-py) and the comments on dask/dask#3121

We need to mention this somewhere on the code or readme, not sure what's the best way to address this.

cc: @jrbourbeau

**Comment by bnaul** [comment]
For the record my @replicahq colleagues @JacobHayes and @mikss were co-authors of that snippet; whatever you guys feel is appropriate is fine, even just tagging us in a changelog like https://github.com/dask/dask/blob/main/docs/source/changelog.rst

**Comment by jrbourbeau** [comment]
We went with a "History" section in the README (https://github.com/coiled/dask-bigquery#history). @bnaul let us know if you'd like an update to any of the wording used, etc.
