### ISSUE TITLE
Release 2023.5

### ISSUE THREAD

**Issue by bnaul** [coiled/dask-bigquery#51]
Anything else we want to get in before doing a release with #44 and #46?

**Comment by bnaul** [comment]
#50 is done! @jrbourbeau @j-bennet @ncclementi shall we?

**Comment by ncclementi** [comment]
+1 for release, @jrbourbeau was there anything else you wanted to go in? If I get the green light I can do the release today

**Comment by bnaul** [comment]
Can't think of any reason it would be needed

**Comment by ncclementi** [comment]
Pypi is ready https://pypi.org/project/dask-bigquery/
waiting for the bots to open the condaforge PR - usually happens within 1-2 hours

I missed that the readme still says "Read data from [Google BigQuery](https://cloud.google.com/bigquery) with Dask." 🤦 
Not sure this is worth another release.

**Comment by ncclementi** [comment]
@bnaul I just ping you over in the feedstock for a final review before we merge the conda-forge release. See https://github.com/conda-forge/dask-bigquery-feedstock/pull/2 just in case, and if you are ok with it feel free to hit the merge button.

**Comment by ncclementi** [comment]
Conda-forge went in this morning. The release is done!
Thank you for all your work, @j-bennet and @bnaul!!
