### ISSUE TITLE
attribute Google API requests to dask/dask-bigquery package

### ISSUE THREAD

**Issue by tswast** [coiled/dask-bigquery#6]
It would be helpful for me and my teammates at Google in the prioritization of our work on open source connectors to have requests initiated by Dask attributable to this connector. The way this is done is by adding a User-Agent header to requests containing the tool name and version.

In Python, the ClintInfo class(es) are used to set this header: https://googleapis.dev/python/google-api-core/latest/client_info.html

```python
from google.api_core import client_info as rest_client_info
from google.api_core.gapic_v1 import client_info as grpc_client_info

bq_client_info = rest_client_info.ClientInfo(
    user_agent=f"dask-bigquery/{dask_bigquery.__version__}"
)
bqstorage_client_info = grpc_client_info.ClientInfo(
    user_agent=f"dask-bigquery/{dask_bigquery.__version__}"
)

with bigquery.Client(project_id, client_info=bq_client_info) as bq_client:
    bq_storage_client = bigquery_storage.BigQueryReadClient(
        credentials=bq_client._credentials,
        client_info=bqstorage_client_info,
    )
    yield bq_client, bq_storage_client
    bq_storage_client.transport.grpc_channel.close()
```

Examples with `google.cloud.bigquery.Client`:

* [ibis-bigquery](https://github.com/ibis-project/ibis-bigquery/blob/86594aa938d1dbfe80c4f7598085c49f4b817e69/ibis_bigquery/client.py#L403)
* [pandas-gbq](https://github.com/googleapis/python-bigquery-pandas/blob/f4a5f734be7fa1c9c5ba9e3508514319243c7b6f/pandas_gbq/gbq.py#L349-L373)
* [jupyter magics](https://github.com/googleapis/python-bigquery/blob/ee1e25c68fff8f35b595a832a582bdd7dd8dc73b/google/cloud/bigquery/magics/magics.py#L633)

**Comment by jrbourbeau** [comment]
Thanks for the suggestion and providing a nice code snippet @tswast! Setting those User-Agent headers sounds totally reasonable and we'll be sure to add them as a follow up to https://github.com/coiled/dask-bigquery/pull/4

cc @ncclementi
