### ISSUE TITLE
Add instruction to run tests locally

### ISSUE THREAD

**Issue by ncclementi** [coiled/dask-bigquery#7]
If someone wants to test things locally they need to be authenticated and have a project created on that account with `project_id="dask-bigquery"`. If they're using a service account, when created they need to select a role of BigQuery Admin in the section "Grant this service account access to project"

**Comment by bnaul** [comment]
That project ID is unique I think, so users wouldn't be able to create another project with the same name. Maybe it could be configurable?

**Comment by ncclementi** [comment]
Oh yes, I forgot that. That's a good point, thanks for pointing that out. Working on something that I believe it fixes it. 
Users would be able to locally do:
`py.test --project_id name_of_their_project_id test_core.py`
