### ISSUE TITLE
allow to_gbq without datasets.create permissions

### ISSUE THREAD

**Issue by bolliger32** [coiled/dask-bigquery#73]
Currently, due to https://github.com/coiled/dask-bigquery/blob/b6d5b04e544350b2dd46e10221844d56024e92ba/dask_bigquery/core.py#L312, you cannot execute to_gbq in the situation where a dataset already exists but you do not have datasets.create permissions. Perhaps it would make sense to try `get_dataset` first, and if that doesn't work, call `create_dataset`. That would handle this situation I believe.

**Comment by j-bennet** [comment]
Hi @bolliger32, thank you for reporting. Looks like you know how to fix the problem already, too! If you feel up to it, I would encourage you to submit a PR, we'd be happy to accept it.
