### ISSUE TITLE
Can a new release be created for new changes?

### ISSUE THREAD

**Issue by nick-amplify** [coiled/dask-bigquery#82]
The read_gbq command [now takes creds](https://github.com/coiled/dask-bigquery/pull/78), but I have to install the package with: `dask-bigquery @ git+https://github.com/coiled/dask-bigquery.git@main` because this isn't included in the latest release

**Comment by jrbourbeau** [comment]
Yeah, we can definitely cut a new release

Btw, is the new creds options working well for you?

**Comment by nick-amplify** [comment]
@jrbourbeau yup! has worked great

**Comment by jrbourbeau** [comment]
Great, glad to hear it

`dask-bigquery=2023.9.0` (which has the new creds option) is out on PyPI. I'll close this issue once the release is out on conda-forge (should be there shortly https://github.com/conda-forge/dask-bigquery-feedstock/pull/4)

**Comment by jrbourbeau** [comment]
Closing as the conda-forge recipe has been updated for 2023.9.0 👍
