### ISSUE TITLE
DataFrame object returned by `dask_bigquery.read_gbq` isn't an instance of `dask.dataframe.DataFrame`

### ISSUE THREAD

**Issue by kzvezdarov** [coiled/dask-bigquery#84]
The object returned by `dask_biguery.read_gbq` isn't an instance of `dask.dataframe.DataFrame`:
```python
In [17]: import dask

In [18]: import dask_bigquery

In [19]: ddf = dask_bigquery.read_gbq(project_id, dataset_id, table_id)

In [20]: isinstance(ddf, dask.dataframe.DataFrame)
Out[20]: False
```

This is an issue for code that relies on `isinstance` to be able to differentiate between Pandas and Dask dataframes - for example `dask_sql` will fail to create a table from such a dataframe because it tries to process it as a Pandas dataframe due to [`dask_sql.input_utils.dask.DaskInputPlugin.is_correct_input`](https://github.com/dask-contrib/dask-sql/blob/main/dask_sql/input_utils/dask.py#L11-L14) producing a false negative and [`dask_sql.input_utils.pandaslike.PandasLikeInputPlugin.is_correct_input`](https://github.com/dask-contrib/dask-sql/blob/main/dask_sql/input_utils/pandaslike.py#L10-L16) producing a false positive:
```python
In [23]: import dask_sql

In [24]: context = dask_sql.Context()

In [25]: context.create_table("data", ddf)

TypeError: Trying to convert dd.Scalar<monoton..., dtype=bool> to a boolean value. Because Dask objects are lazily evaluated, they cannot be converted to a boolean value or used in boolean conditions like if statements. Try calling .compute() to force computation prior to converting to a boolean value or using in a conditional statement.
```

Recreating it by converting to delayed and back into a dataframe seems to fix that:
```python
In [21]: recreated_ddf = dask.dataframe.from_delayed(ddf.to_delayed())

In [22]: isinstance(recreated_ddf, dask.dataframe.DataFrame)
Out[22]: True
```

And allows for `dask_sql` to create a table from it properly:
```python
In [26]: context.create_table("data", recreated_ddf)

In [27]:
```

**Comment by phofl** [comment]
Could you try this with main? I am reasonable certain that we merged a PR last week that should address this

**Comment by kzvezdarov** [comment]
@phofl Yup, works correctly with `main`.

**Comment by phofl** [comment]
I'll close this one then, we will release later this week
